<a href="https://colab.research.google.com/github/pranaypratik-iitp/my_pytorch_practice/blob/main/autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

autograd is a core component of pytorch that provides automatic diffrentiation for tensor operations and it enables gradient computation ,which is
essential for training ml modules using optimization algorithms like gradient descent

In [23]:
import torch

STEP 1 : define a tensor for x and y both , while defining tensor there is an attribute -- requires_grad=True -- that means pytorch will automatically understands that we are more interested in calculation grad of x

In [24]:
x= torch.tensor(6.0,requires_grad=True)

STEP 2 : creted a relationship between y and x on which the gradient is going to be calculated.

In [25]:
y=x**2

In [26]:
x

tensor(6., requires_grad=True)

In [27]:
y  # powerbackward --- remebered by pytorch that we have to calculate our gradient based on power

tensor(36., grad_fn=<PowBackward0>)

In [28]:
y.backward()  # backward is used to calculate derivative of the relationship btw x and y

In [30]:
x.grad   # to calculate gradient use grad function

tensor(12.)

eg : 2 y= x**2 , z= sin(y)

In [9]:
x=torch.tensor(4.0,requires_grad=True)

In [10]:
y=x**2

In [11]:
z=torch.sin(y)

In [12]:
x

tensor(4., requires_grad=True)

In [13]:
y

tensor(16., grad_fn=<PowBackward0>)

In [14]:
z

tensor(-0.2879, grad_fn=<SinBackward0>)

In [15]:
z.backward()

In [16]:
x.grad

tensor(-7.6613)

In [31]:
y.grad  # error as y is an intermidiate node so in pytorch this is not allowed. gradients in pytorch allows only root node and leaf node.

/tmp/ipykernel_2699/3065606373.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more information. (Triggered internally at /pytorch/build/aten/src/ATen/core/TensorBody.h:494.)
  y.grad  # error as y is an intermidiate node so in pytorch this is not allowed. gradients in pytorch allows only root node and leaf node.


Designing a neural network having 2 cols 1. cgpa 2. placement and activation function used is sigmoid

In [32]:
import torch

In [33]:
x=torch.tensor(6.7)  # input feature
y=torch.tensor(0.0)  # true label(binary)

w=torch.tensor(1.0)  # weights
b=torch.tensor(0.0)  # bias

In [34]:
# binary cross entropy loss for scalar
def binary_cross_entropy_loss(prediction,target):
  epsilon=1e-8      # to prevent log(0)
  prediction=torch.clamp(prediction,epsilon,1-epsilon)
  return -(target*torch.log(prediction)+(1-target)*torch.log(1-prediction))

In [35]:
# forward pass:
z=w*x+b # weighted sum(linear part)
y_pred=torch.sigmoid(z)


# compute binary loss:
loss=binary_cross_entropy_loss(y_pred,y)

In [36]:
# derivatives:
dloss_dy_pred=(y_pred-y)/(y_pred*(1-y_pred))

In [37]:
# using autograd
x=torch.tensor(6.7)
y=torch.tensor(0.0)


In [38]:
w=torch.tensor(1.0,requires_grad=True)
b=torch.tensor(0.0,requires_grad=True)

In [39]:
w

tensor(1., requires_grad=True)

In [40]:
b

tensor(0., requires_grad=True)

In [41]:
z=w*x+b
z

tensor(6.7000, grad_fn=<AddBackward0>)

In [42]:
y_pred=torch.sigmoid(z)
y_pred

tensor(0.9988, grad_fn=<SigmoidBackward0>)

In [44]:
loss=binary_cross_entropy_loss(y_pred,y)
loss

tensor(6.7012, grad_fn=<NegBackward0>)

In [45]:
loss.backward()

In [46]:
w.grad

tensor(6.6918)

In [47]:
b.grad

tensor(0.9988)

EARLIER WE HAVE DONE CALCULATIONS ON SCALARS ONLY BUT NOW WE ARE GOING TO CALCULATE FOR VECTORS TOO

In [49]:
x=torch.tensor([1.0,2.0,3.0],requires_grad=True)
x

tensor([1., 2., 3.], requires_grad=True)

In [51]:
y=(x**2).mean()
y

tensor(4.6667, grad_fn=<MeanBackward0>)

In [52]:
y.backward()

In [53]:
x.grad

tensor([0.6667, 1.3333, 2.0000])

**CLEARING GRADIENTS**

In pytorch gradients are not going to clear automatically as it starts accumulating like if we got 4 as gradient and again if we are going to calculate the same gradient then instead of 4 it will add 4 to it and the new grad will be 8.

In [54]:
x.grad.zero_()  # clearing gradient

tensor([0., 0., 0.])

**disabling gradient tracking**

In [56]:
# option 1:
x.requires_grad_(False)
x

tensor([1., 2., 3.])

In [57]:
y=x**2

In [58]:
y.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [59]:
# option 2 : detach:  make a completely new function
z=x.detach()
z


tensor([1., 2., 3.])

In [60]:
y=x**2
y.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [62]:
# option 3 : torch.nograd():
x=torch.tensor(2.0,requires_grad=True)
x

tensor(2., requires_grad=True)

In [63]:
with torch.no_grad():
  y=x**2

In [64]:
y

tensor(4.)

In [65]:
y.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn