<a href="https://colab.research.google.com/github/pranaypratik-iitp/my_pytorch_practice/blob/main/pytorch__NN_Module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Today we will much interested in optimizing the nn module

1. building the neural network using NN module
2. using bulit-in activation function
3. using built-in loss function
4. using built-in optimizer



**The NN Module**
building any neaural network is a very hectic task to do as making connection between loss


*   The torch.nn module in pytorch is a core library that provides a wide array of classe & functions designed to help developers build neural network efficiently and effective.




**Key components of torch.nn**



1. modules(layers):

    1. nn.module : the base class for all the neural network modules. your custom models and layers should subclass this class
    2. common layer : icludes layers like nn.linear (fully connected layers) nn.conv2d(convolution layer) nn.lstm(recurrent layer) and many others



2. Activation function:


*   functions like ReLU, nn.sigmoid, nn.tanhintroduce non-linearity to the model, allowing it to learn complex patterns



3. loss function: provides loss function such as nn.crossEntropyLoss, nn.MSEloss and nn.NLLLOSS
2.  container modules : nn.Sequential


4. Regulation and dropout : layers like nn.dropout and nn.batchNorm2d helps preventing overfitting and improves the model's ability to generalize to new data










In [2]:
# create model class: 5 inputs features with one neuron giving one output
import torch
import torch.nn as nn

In [3]:
class Model(nn.Module):
  def __init__(self,num_features):          # num_features defines how much feature you want
    super().__init__()
    self.linear=nn.Linear(num_features,1)  # num_features - no. of input features and 1: no of output
    self.sigmoid = nn.Sigmoid()             # activation function

  def forward(self,features):
    out=self.linear(features)         # calculating z here means wx+b
    out=self.sigmoid(out)

    return out

In [4]:
# create dataset
features=torch.randn(10,5)      # dummy dataset with 10 rows and 5 columns (equals to num of fearures)

# create model
model=Model(features.shape[1])  # created object of the model and features.shape[1] - signifies the num of features

# call model for forward pass

model(features)

tensor([[0.4305],
        [0.6145],
        [0.5936],
        [0.4517],
        [0.5664],
        [0.5067],
        [0.4227],
        [0.6590],
        [0.7890],
        [0.4657]], grad_fn=<SigmoidBackward0>)

In [5]:
# showing model weights
model.linear.weight

Parameter containing:
tensor([[ 0.3346, -0.1739,  0.0323,  0.1340, -0.3794]], requires_grad=True)

In [6]:
# showing model bias
model.linear.bias

Parameter containing:
tensor([0.1329], requires_grad=True)

In [7]:
!pip install torchinfo #to visualize the whole thing in pytorch

In [8]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [9]:
import torch
import torch.nn as nn
class Model(nn.Module):
  def __init__(self,num_features):          # num_features defines how much feature you want
    super().__init__()
    self.linear1=nn.Linear(num_features,3)  # num_features - no. of input features and 3: no of output
    self.relu = nn.ReLU()             # activation function
    self.linear2=nn.Linear(3,1)
    self.sigmoid=nn.Sigmoid()

  def forward(self,features):
    out=self.linear1(features)         # calculating z here means wx+b
    out=self.relu(out)
    out=self.linear2(out)
    out=self.sigmoid(out)

    return out

In [10]:
# create dataset
features=torch.randn(10,5)      # dummy dataset with 10 rows and 5 columns (equals to num of fearures)

# create model
model=Model(features.shape[1])  # created object of the model and features.shape[1] - signifies the num of features

# call model for forward pass

model(features)

tensor([[0.4838],
        [0.3892],
        [0.4174],
        [0.3892],
        [0.4597],
        [0.4221],
        [0.4795],
        [0.4502],
        [0.4148],
        [0.4668]], grad_fn=<SigmoidBackward0>)

In [11]:
model.linear1.weight

Parameter containing:
tensor([[ 0.1481, -0.4085,  0.2575, -0.4246, -0.1000],
        [-0.4180, -0.0966, -0.1373, -0.3829, -0.0874],
        [ 0.4443, -0.1507,  0.4321, -0.3986,  0.1820]], requires_grad=True)

In [12]:
model.linear2.weight

Parameter containing:
tensor([[-0.2831,  0.5428,  0.3981]], requires_grad=True)

In [13]:
model.linear1.bias

Parameter containing:
tensor([0.0525, 0.0948, 0.2663], requires_grad=True)

In [14]:
model.linear2.bias

Parameter containing:
tensor([-0.4505], requires_grad=True)

In [15]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

while doing forward pass it is very difficult to do so . to make it easy we can use SEQUENTIAL CONTAINERS

In [17]:
import torch
import torch.nn as nn
class Model(nn.Module):
  def __init__(self,num_features):          # num_features defines how much feature you want
    super().__init__()
    self.network=nn.Sequential(
        nn.Linear(num_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )

  def forward(self,features):
    out=self.network(features)         # calculating z here means wx+b


    return out

In [18]:
# create dataset
features=torch.randn(10,5)      # dummy dataset with 10 rows and 5 columns (equals to num of fearures)

# create model
model=Model(features.shape[1])  # created object of the model and features.shape[1] - signifies the num of features

# call model for forward pass

model(features)

tensor([[0.6307],
        [0.5920],
        [0.6689],
        [0.5669],
        [0.4995],
        [0.6221],
        [0.5552],
        [0.4995],
        [0.5392],
        [0.6982]], grad_fn=<SigmoidBackward0>)

do the training_pipeline_nn module with these transformation