<a href="https://colab.research.google.com/github/pranaypratik-iitp/my_pytorch_practice/blob/main/pytorch1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)

2.11.0+cu128


In [3]:
if torch.cuda.is_available():
  print('GPU is available !')
  print(f"Using GPU : {torch.cuda.get_device_name(0)}")
else:
  print('GPU is not available. Using CPU.')

GPU is available !
Using GPU : Tesla T4


**Creating** a **Tensor**

In [4]:
# using empty
torch.empty(2,3)  # empty allocates memory

a=torch.empty(2,3)
type(a)

torch.Tensor

In [5]:
# using zeros
torch.zeros(2,3)    # all are zero only

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
# using rand
torch.rand(2,3)

tensor([[0.9933, 0.0681, 0.3108],
        [0.6830, 0.4194, 0.8231]])

In [8]:
# use of seed - whenever we use torch.rand all the time we run it will be changed so to let it not to change we use seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [9]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

**Using** **Tensor**

In [10]:
torch.tensor([[1,2,3,4],[2,4,6,8]])

tensor([[1, 2, 3, 4],
        [2, 4, 6, 8]])

**Other Ways**

In [11]:
# arange:
torch.arange(0,10,3)

tensor([0, 3, 6, 9])

In [12]:
# linspace:(linearly spaced)
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [13]:
# using full:()
torch.full((3,3),15)

tensor([[15, 15, 15],
        [15, 15, 15],
        [15, 15, 15]])

In [14]:
# using eye:(identity matrix)
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

**Tensor Shape**

In [15]:
k=torch.tensor([[2,3,4],[5,6,7]])
k.shape

torch.Size([2, 3])

In [16]:
# sometimes you want a tensor same as a given tensor then use:
torch.empty_like(k)

tensor([[    140548925709264,           427770480,                   0],
        [                  0,                   0, 7310593858020254331]])

In [17]:
torch.zeros_like(k)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [18]:
torch.ones_like(k)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [19]:
torch.rand_like(k)

NotImplementedError: "check_uniform_bounds" not implemented for 'Long'

**Tensor Data Types:**


In [20]:
# finding datatype:
k.dtype

torch.int64

In [21]:
# assigning datatype:
torch.tensor([1.0,2.0,4.0,5.0,8.0],dtype=torch.int32)

tensor([1, 2, 4, 5, 8], dtype=torch.int32)

In [22]:
# Tensors already exists and need to change datatype then:
k.to(torch.float32)

tensor([[2., 3., 4.],
        [5., 6., 7.]])

**Mathematical Operation**

1. Scalar operation

In [23]:
l=torch.rand(3,3)
l

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356],
        [0.7118, 0.7876, 0.4183]])

In [24]:
# addition
l+2

tensor([[2.2627, 2.0428, 2.2080],
        [2.1180, 2.1217, 2.7356],
        [2.7118, 2.7876, 2.4183]])

In [25]:
# subtraction
l-2

tensor([[-1.7373, -1.9572, -1.7920],
        [-1.8820, -1.8783, -1.2644],
        [-1.2882, -1.2124, -1.5817]])

In [26]:
# division
l/2

tensor([[0.1313, 0.0214, 0.1040],
        [0.0590, 0.0608, 0.3678],
        [0.3559, 0.3938, 0.2092]])

In [27]:
# multiplication
l*2

tensor([[0.5254, 0.0857, 0.4161],
        [0.2361, 0.2434, 1.4712],
        [1.4235, 1.5752, 0.8366]])

In [28]:
# mod
l%2

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356],
        [0.7118, 0.7876, 0.4183]])

In [29]:
# power
l**2

tensor([[0.0690, 0.0018, 0.0433],
        [0.0139, 0.0148, 0.5411],
        [0.5066, 0.6203, 0.1750]])

2. Elementwise operation

In [30]:
a=torch.rand(2,2)
b=torch.rand(2,2)
print(a,b)

tensor([[0.9014, 0.9969],
        [0.7565, 0.2239]]) tensor([[0.3023, 0.1784],
        [0.8238, 0.5557]])


In [31]:
# addition
a+b

tensor([[1.2038, 1.1753],
        [1.5804, 0.7796]])

In [32]:
# subration
a-b

tensor([[ 0.5991,  0.8185],
        [-0.0673, -0.3319]])

In [33]:
# multiplication
a*b

tensor([[0.2725, 0.1779],
        [0.6232, 0.1244]])

In [34]:
# division
a/b

tensor([[2.9814, 5.5873],
        [0.9183, 0.4029]])

In [35]:
# power
a**b

tensor([[0.9691, 0.9994],
        [0.7946, 0.4353]])

In [36]:
c=torch.tensor([1,-2,-9,3,4])

In [37]:
# absolute value
torch.abs(c)

tensor([1, 2, 9, 3, 4])

In [38]:
# negative value
torch.neg(c)


tensor([-1,  2,  9, -3, -4])

In [39]:
d= torch.tensor([1.2,3.4,5.6,7.8])

In [40]:
# round
torch.round(d)

tensor([1., 3., 6., 8.])

In [41]:
# ceil
torch.ceil(d)

tensor([2., 4., 6., 8.])

In [42]:
# floor
torch.floor(d)

tensor([1., 3., 5., 7.])

In [43]:
# clamp  : it keeps all numbers in a range
torch.clamp(d,min=1.5,max=4)

tensor([1.5000, 3.4000, 4.0000, 4.0000])

3. Reduction Operation

In [52]:
e= torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
e

tensor([[0., 7., 0.],
        [0., 9., 5.]])

In [53]:
# sum
torch.sum(e)
torch.sum(e,dim=0)
torch.sum(e,dim=1)

tensor([ 7., 14.])

In [54]:
# mean
torch.mean(e)  # error is because it one finds the mean of float values but here it is int so go and change data types to float32 then it will work

tensor(3.5000)

In [57]:
# median:
torch.median(e)
torch.median(e,dim=0)
torch.median(e,dim=1)

torch.return_types.median(
values=tensor([0., 5.]),
indices=tensor([2, 2]))

In [59]:
# max and min
torch.max(e)

tensor(9.)

In [61]:
# product
torch.prod(e)

tensor(0.)

In [62]:
# standard deviation
torch.std(e)

tensor(4.0373)

In [63]:
# variance:
torch.var(e)

tensor(16.3000)

In [64]:
# argmax:
torch.argmax(e) # tells the position of the largest number

tensor(4)

In [65]:
# argmin
torch.argmin(e)  # tells the position of the smallest number

tensor(0)

4. Matrix Operation

In [69]:
f=torch.randint(size=(2,3),low=0,high=10)
g=torch.randint(size=(3,2),low=0,high=10)
print(f)
print(g)

tensor([[6, 7, 7],
        [8, 3, 6]])
tensor([[1, 5],
        [5, 0],
        [4, 3]])


In [70]:
# matrix mul:
torch.matmul(f,g)

tensor([[69, 51],
        [47, 58]])

In [71]:
# dot product between two vectors
vector1=torch.tensor([1,2])
vector2=torch.tensor([3,4])
torch.dot(vector1,vector2)

tensor(11)

In [75]:
# traspose
torch.transpose(f,0,1)

tensor([[6, 8],
        [7, 3],
        [7, 6]])

In [79]:
# deteminant
h=torch.randint(size=(4,4),low=0,high=10,dtype=torch.float32)
torch.det(h)

tensor(175.0000)

In [80]:
# inverse:
torch.inverse(h)

tensor([[-1.9868e-08, -5.7143e-02, -2.8571e-02,  2.5714e-01],
        [ 6.0000e-01,  3.8286e-01, -1.1086e+00, -6.2286e-01],
        [ 2.0000e-01, -5.7143e-03, -1.0286e-01, -2.7429e-01],
        [-4.0000e-01, -7.4286e-02,  6.6286e-01,  4.3429e-01]])

5. comparision operation

In [81]:
i=torch.randint(size=(2,3),low=0,high=10)
j=torch.randint(size=(2,3),low=0,high=10)
print(i)
print(j)

tensor([[4, 7, 2],
        [5, 6, 1]])
tensor([[4, 5, 6],
        [9, 2, 3]])


In [82]:
i>j

tensor([[False,  True, False],
        [False,  True, False]])

In [83]:
i<j

tensor([[False, False,  True],
        [ True, False,  True]])

In [84]:
i==j

tensor([[ True, False, False],
        [False, False, False]])

In [85]:
i!=j

tensor([[False,  True,  True],
        [ True,  True,  True]])

In [86]:
i>=j

tensor([[ True,  True, False],
        [False,  True, False]])

In [87]:
i<=j

tensor([[ True, False,  True],
        [ True, False,  True]])

6. special functions

In [102]:
k=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
k

tensor([[9., 2., 4.],
        [6., 6., 8.]])

In [103]:
# log
torch.log(k)

tensor([[2.1972, 0.6931, 1.3863],
        [1.7918, 1.7918, 2.0794]])

In [104]:
# exponent
torch.exp(k)

tensor([[8.1031e+03, 7.3891e+00, 5.4598e+01],
        [4.0343e+02, 4.0343e+02, 2.9810e+03]])

In [105]:
# sqrt
torch.sqrt(k)

tensor([[3.0000, 1.4142, 2.0000],
        [2.4495, 2.4495, 2.8284]])

In [106]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9999, 0.8808, 0.9820],
        [0.9975, 0.9975, 0.9997]])

In [107]:
# softmax
torch.softmax(k,dim=0)

tensor([[0.9526, 0.0180, 0.0180],
        [0.0474, 0.9820, 0.9820]])

In [108]:
# relu
torch.relu(k)

tensor([[9., 2., 4.],
        [6., 6., 8.]])

7. INPLACE OPERATIONS

In [109]:
# SUPPOSE WE ARE WORKING ON A LARGE DATASET AND THERE IS A PROBLEM OF SPACE AND WHENEVER YOU ARE GOING TO PERFORM ANY OPERATION BETWEEN ANY TWO MATRIX
# THE RESULT WILL BE STORED INTO A NEW TENSOR

In [112]:
m=torch.rand(2,3)
n=torch.rand(2,3)

In [113]:
m+n

tensor([[1.1222, 0.3315, 1.8549],
        [1.2494, 0.9331, 0.5003]])

In [114]:
m.add_(n)

tensor([[1.1222, 0.3315, 1.8549],
        [1.2494, 0.9331, 0.5003]])

In [115]:
m

tensor([[1.1222, 0.3315, 1.8549],
        [1.2494, 0.9331, 0.5003]])

In [117]:
n

tensor([[0.5534, 0.2682, 0.9556],
        [0.9761, 0.5934, 0.3124]])

In [118]:
m.relu_()

tensor([[1.1222, 0.3315, 1.8549],
        [1.2494, 0.9331, 0.5003]])

In [119]:
# note: if you want to inplace permanent changes then pick any function and apply _ after it

8. Copying a Tensor

In [121]:
a=torch.rand(2,3)
a

tensor([[0.3847, 0.4521, 0.5569],
        [0.9952, 0.0015, 0.0813]])

In [126]:
# in python
b=a
b # both both are at same location so if you make changes to a it will reflect on b too

tensor([[0.3023, 0.1784],
        [0.8238, 0.5557]])

In [134]:
b=a.clone()
print(b)
print(id(a),id(b))

tensor([[0.3023, 0.1784],
        [0.8238, 0.5557]])
140548711537136 140543678622976


9. TENSOR OPERATIONS ON GPU

In [135]:
torch.cuda.is_available()


True

In [136]:
device=torch.device('cuda')

In [138]:
# creating new tensor on gpu
torch.rand(2,3,device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [142]:
# moving an existing tensor on gpu
x=a.to(device)
x
x+5

tensor([[5.3023, 5.1784],
        [5.8238, 5.5557]], device='cuda:0')